# Cloud Build configuration to run Prisma migrations
# This can be triggered manually or as part of deployment pipeline

steps:
  # Install dependencies and run migrations
  # Note: Source code is already uploaded by gcloud builds submit
  # Using Unix socket connection format (no Cloud SQL Proxy needed)
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        npm install
        echo "Generating Prisma client..."
        npx prisma generate
        echo "Running migrations..."
        npx prisma migrate deploy
        echo "✅ Migrations completed successfully!"
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
    id: 'run-migrations'

# Substitution variables
substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'startege:us-central1:startege-db'
  _DATABASE_URL: 'postgresql://postgres:Zoya%4057Bruce@localhost/startege?host=/cloudsql/startege:us-central1:startege-db'

# Options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '600s'


