# Cloud Build configuration to run Prisma migrations
# This can be triggered manually or as part of deployment pipeline

steps:
  # Install dependencies and run migrations
  # Start Cloud SQL Proxy in background, then run migrations
  # Cloud Build doesn't have Unix sockets, so we use TCP via Cloud SQL Proxy
  - name: 'node:20-alpine'
    id: 'run-migrations'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Install Cloud SQL Proxy
        echo "Installing Cloud SQL Proxy..."
        wget -q https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.alpine -O /tmp/cloud-sql-proxy
        chmod +x /tmp/cloud-sql-proxy
        
        # Start Cloud SQL Proxy in background
        /tmp/cloud-sql-proxy --port=5432 $${_CLOUD_SQL_CONNECTION_NAME} &
        PROXY_PID=$$!
        
        # Wait for proxy to be ready
        echo "Waiting for Cloud SQL Proxy to start..."
        apk add --no-cache netcat-openbsd
        for i in 1 2 3 4 5 6 7 8 9 10; do
          if nc -z 127.0.0.1 5432 2>/dev/null; then
            echo "Cloud SQL Proxy is ready!"
            break
          fi
          echo "Waiting... ($i/10)"
          sleep 2
        done
        
        # Install dependencies and apply schema
        echo "Installing dependencies..."
        npm install
        echo "Generating Prisma client..."
        npx prisma generate
        
        # Apply schema directly (more reliable than migrate deploy for initial setup)
        echo "Applying database schema..."
        npx prisma db push --accept-data-loss --skip-generate
        
        echo "✅ Schema applied successfully!"
        
        # Stop the proxy
        kill $$PROXY_PID 2>/dev/null || true
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}'

# Substitution variables
substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'startege:us-central1:startege-db'
  # Cloud Build uses TCP via Cloud SQL Proxy (not Unix sockets)
  _DATABASE_URL: 'postgresql://postgres:Zoya%4057Bruce@127.0.0.1:5432/startege'

# Options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '600s'


