# Cloud Build configuration to run Prisma migrations
# This can be triggered manually or as part of deployment pipeline

steps:
  # Install dependencies and run migrations
  # Start Cloud SQL Proxy in background, then run migrations
  # Cloud Build doesn't have Unix sockets, so we use TCP via Cloud SQL Proxy
  - name: 'gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0'
    id: 'run-migrations'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Start Cloud SQL Proxy in background
        /cloud-sql-proxy --port=5432 $${_CLOUD_SQL_CONNECTION_NAME} &
        PROXY_PID=$$!
        
        # Wait for proxy to be ready
        echo "Waiting for Cloud SQL Proxy to start..."
        for i in 1 2 3 4 5 6 7 8 9 10; do
          if nc -z 127.0.0.1 5432 2>/dev/null; then
            echo "Cloud SQL Proxy is ready!"
            break
          fi
          echo "Waiting... ($i/10)"
          sleep 2
        done
        
        # Install dependencies and run migrations
        echo "Installing dependencies..."
        apk add --no-cache nodejs npm postgresql-client
        npm install
        echo "Generating Prisma client..."
        npx prisma generate
        echo "Running migrations..."
        npx prisma migrate deploy
        echo "✅ Migrations completed successfully!"
        
        # Stop the proxy
        kill $$PROXY_PID 2>/dev/null || true
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}'

# Substitution variables
substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'startege:us-central1:startege-db'
  # Cloud Build uses TCP via Cloud SQL Proxy (not Unix sockets)
  _DATABASE_URL: 'postgresql://postgres:Zoya%4057Bruce@127.0.0.1:5432/startege'

# Options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '600s'


